### ISSUE TITLE
variable has no attribute of 'set_value' after switch to tensorflow

### ISSUE THREAD

**Issue by weiliu620** [GUR9000/KerasNeuralFingerprint#2]
Fond this error after setting Keras backend to Tensorflow:

```
In [3]: run train_fingerprint_model.py
Using TensorFlow backend.
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
Naive baseline (using mean): MSE = 4.39096012147 (RMSE = 2.09546179194 )

crossvalidation split 1 of 10
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
name: GeForce GTX 980 Ti
major: 5 minor: 2 memoryClockRate (GHz) 1.076
pciBusID 0000:03:00.0
Total memory: 6.00GiB
Free memory: 5.28GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:839] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 980 Ti, pci bus id: 0000:03:00.0)
starting training (compiling)...
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/home/weiliu/projects/KerasNeuralFingerprint/train_fingerprint_model.py in <module>()
    239 
    240 
--> 241     main(1)
    242 
    243 

/home/weiliu/projects/KerasNeuralFingerprint/train_fingerprint_model.py in main(use_matrix_based_implementation)
    217 
    218         model, train_mse_at_valbest, val_mse_best, test_mse_at_valbest = train_model(model, train, valid_data, test_data, 
--> 219                                      batchsize = batchsize, num_epochs = num_epochs, train=1)
    220         train_mse.append(train_mse_at_valbest)
    221         val_mse.append(val_mse_best)

/home/weiliu/projects/KerasNeuralFingerprint/train_fingerprint_model.py in train_model(model, train_data, valid_data, test_data, batchsize, num_epochs, train, initial_lr, total_lr_decay, verbose)
     99         times=[]
    100         for epoch in range(num_epochs):
--> 101             update_lr(model, initial_lr, epoch*1./num_epochs, total_lr_decay)
    102             batch_order = np.random.permutation(len(train_data))
    103             losses=[]

/home/weiliu/projects/KerasNeuralFingerprint/train_fingerprint_model.py in update_lr(model, initial_lr, relative_progress, total_lr_decay)
     63     """
     64     assert total_lr_decay > 0 and total_lr_decay <= 1
---> 65     model.optimizer.lr.set_value(initial_lr * total_lr_decay**(relative_progress))
     66 
     67 

AttributeError: 'Variable' object has no attribute 'set_value'
```

**Comment by GUR9000** [comment]
fixed; using backend.set_value() now.

**Comment by Aliases** [comment]
I am still getting the same error. I installed keras with tensorflow backend 2 days back.

  File "/home/aananya/Softwares/anaconda3/envs/tf/lib/python3.5/site-packages/keras/engine/training.py", line 1401, in fit_generator
    callbacks.on_epoch_begin(epoch)
  File "/home/aananya/Softwares/anaconda3/envs/tf/lib/python3.5/site-packages/keras/callbacks.py", line 35, in on_epoch_begin
    callback.on_epoch_begin(epoch, logs)
  File "/home/aananya/Softwares/anaconda3/envs/tf/lib/python3.5/site-packages/keras/callbacks.py", line 424, in on_epoch_begin
    lr = self.schedule(epoch)
  File "nn.py", line 122, in lr_scheduler
    model.optimizer.lr.set_value(np.float32(decay \* model.optimizer.lr.get_value()))
AttributeError: 'Variable' object has no attribute 'set_value'

**Comment by GUR9000** [comment]
I think that you are in the wrong github repo for this problem.... but in any case: TENSOR.set_value and TENSOR.get_value only work in Theano. You have to use keras.backend.set_value() and keras.backend.get_value()

**Comment by Aliases** [comment]
Yes, that helped. Thanks.
